name: Test

on:
  push:
    branches:
      - main
      - staging
  pull_request:

env:
  RUBY_VERSION: 3.2.8
  NODE_VERSION: 18.17.1
  RAILS_ENV: test
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_HOST: localhost
  RUBYOPT: '-W:no-deprecated'
  CHROME_VERSION: 126.0.6478.182

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: ${{ env.CHROME_VERSION }}

      - name: List Chrome
        run: apt list --installed | grep chrome
    
      - name: Remove Chrome
        run: sudo apt remove google-chrome-stable
    
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: ${{ env.CHROME_VERSION }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - run: bundle exec rubocop -P
        name: Lint Ruby files

      - name: Setup & create Database
        run: |
          bundle exec rails db:create db:schema:load

      - name: Precompile assets
        run: |
          npm ci
          bundle exec rake assets:precompile
        env:
          RAILS_ENV: production
          DB_ADAPTER: nulldb
          SECRET_KEY_BASE: 1234567890

      - name: Run RSpec
        run: SIMPLECOV=1 CODECOV=1 bundle exec rspec
